In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data=pd.read_csv('C:\\Users\\Abdullah-PC\\Desktop\\digit-recognizer\\train.csv')
data.head(10)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   
5      0       0       0       0       0       0       0       0       0   
6      7       0       0       0       0       0       0       0       0   
7      3       0       0       0       0       0       0       0       0   
8      5       0       0       0       0       0       0       0       0   
9      3       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   
5       0  ...         0         0         0         0         0         0   
6       0  ...         0         0         0         0         0         0   
7       0  ...         0         0         0         0         0         0   
8       0  ...         0         0         0         0         0         0   
9       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  
5         0         0         0         0  
6         0         0         0         0  
7         0         0         0         0  
8         0         0         0         0  
9         0         0         0         0  

[10 rows x 785 columns]

In [3]:
data = np.array(data)
m , n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
x_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]


In [5]:
def init_params():
    W1 = np.random.randn(25,784)
    b1 = np.zeros((25,1))
    W2 = np.random.randn(10,25)
    b2 = np.zeros((10,1))

    return W1,b1,W2,b2
def ReLU(Z):
    return np.maximum(0,Z)
def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z),axis=0)

def forward_prop(W1,b1,W2,b2,X):
    Z1 = np.dot(W1,X) + b1
    A1 = ReLU(Z1)
    Z2 = np.dot(W2,A1) + b2
    A2 = softmax(Z2)
    return Z1,A1,Z2,A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size,Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z>0

def back_prop(Z1,A1,Z2,A2,W1,W2,X,Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = (1/m) * np.dot(dZ2,A1.T)
    db2 = (1/m) * np.sum(dZ2,axis=1,keepdims=True)
    dZ1 = np.multiply(np.dot(W2.T,dZ2),np.int64(A1>0))
    dW1 = (1/m) * np.dot(dZ1,X.T)
    db1 = (1/m) * np.sum(dZ1,axis=1,keepdims=True)
    return dW1,db1,dW2,db2

def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,learning_rate):
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    return W1,b1,W2,b2

def get_predictions(A2):
    return np.argmax(A2,axis=0)

def get_accuracy(predictions,Y):
    print(predictions,Y)
    return np.sum(predictions==Y)/Y.size

def gradient_descent(X,Y,learning_rate,iterations):
    W1,b1,W2,b2 = init_params()
    for i in range(iterations):
        Z1,A1,Z2,A2 = forward_prop(W1,b1,W2,b2,X)
        dW1,db1,dW2,db2 = back_prop(Z1,A1,Z2,A2,W1,W2,X,Y)
        W1,b1,W2,b2 = update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,learning_rate)
        if i%100 == 0:
            print("Iteration: ",i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions,Y))
    return W1,b1,W2,b2

W1,b1,W2,b2 = gradient_descent(X_train,Y_train,0.1,1000)







C:\Users\Abdullah-PC\AppData\Local\Temp\ipykernel_20652\3158896777.py:11: RuntimeWarning: overflow encountered in exp
  return np.exp(Z) / np.sum(np.exp(Z),axis=0)
C:\Users\Abdullah-PC\AppData\Local\Temp\ipykernel_20652\3158896777.py:11: RuntimeWarning: invalid value encountered in divide
  return np.exp(Z) / np.sum(np.exp(Z),axis=0)


Iteration:  0
[5 0 1 ... 1 1 1] [4 4 5 ... 2 3 0]
0.10409756097560975
Iteration:  100
[0 0 0 ... 0 0 0] [4 4 5 ... 2 3 0]
0.09907317073170732
Iteration:  200
[0 0 0 ... 0 0 0] [4 4 5 ... 2 3 0]
0.09907317073170732


KeyboardInterrupt: 